/**
 * Cline hook adapter.
 *
 * Cline runs hooks as executable files named after the event
 * (`.clinerules/hooks/PreToolUse`, …), passing JSON on stdin and reading
 * `{cancel, errorMessage, contextModification}` from stdout. Its payload nests
 * the event data under a key named for the hook:
 *
 *   { "taskId": "…", "workspaceRoots": ["/repo"], "hookName": "PreToolUse",
 *     "preToolUse": { "toolName": "execute_command", "parameters": { "command": "…" } } }
 *
 * Cline's pre-tool hook can cancel but cannot pause for a human, so `ask`
 * becomes a Provenant approval, as in Codex and OpenCode.
 *
 * Cline documents hooks as macOS and Linux only; see adapters/cline/README.md.
 */

import {
  gateToolCall,
  recordOutcome,
  recordPrompt,
  startSession,
  endSession,
  checkpointSession,
} from '../gate.js';
import { renderResponse, approvalMessage } from './common.js';

const HARNESS = 'cline';

/** Read Cline's nested payload into the shape the gate expects. */
export function normalize(payload = {}) {
  const p = payload && typeof payload === 'object' ? payload : {};
  const pre = p.preToolUse ?? p.pre_tool_use ?? {};
  const post = p.postToolUse ?? p.post_tool_use ?? {};
  const prompt = p.userPromptSubmit ?? p.user_prompt_submit ?? {};
  const roots = Array.isArray(p.workspaceRoots) ? p.workspaceRoots : [];
  return {
    harnessSessionId: p.taskId ?? p.task_id ?? null,
    cwd: roots[0] ?? p.cwd ?? process.cwd(),
    tool: pre.toolName ?? post.toolName ?? null,
    input: pre.parameters ?? post.parameters ?? {},
    result: post.result,
    success: post.success,
    prompt: prompt.prompt ?? prompt.text ?? p.prompt ?? '',
    model: typeof p.model === 'object' && p.model ? p.model.id ?? p.model.modelId : p.model,
    reason: p.hookName ?? 'end',
  };
}

/**
 * @param {string} event
 * @param {object} payload
 * @returns {{stdout: object, exitCode: number}}
 */
export function handle(event, payload) {
  const p = normalize(payload);
  const common = { harnessSessionId: p.harnessSessionId, harness: HARNESS, cwd: p.cwd };

  switch (event) {
    case 'task-start':
    case 'task-resume':
      startSession({ ...common, model: p.model });
      return proceed();

    case 'prompt':
      recordPrompt({ ...common, prompt: p.prompt });
      return proceed();

    case 'pre-tool': {
      if (!p.tool) return proceed();
      const d = gateToolCall({ ...common, tool: p.tool, input: p.input, askMode: 'approval' });
      if (d.effect === 'allow') return proceed();
      const message =
        d.effect === 'ask' ? approvalMessage(d) : `Blocked by Provenant [${d.class}]: ${d.reason}`;
      // errorMessage is shown for the cancelled call; contextModification keeps
      // the reason in the conversation so the model adapts instead of retrying.
      return { stdout: { cancel: true, errorMessage: message, contextModification: message }, exitCode: 0 };
    }

    case 'post-tool':
      if (!p.tool) return proceed();
      recordOutcome({
        ...common,
        tool: p.tool,
        input: p.input,
        output: renderResponse(p.result),
        ok: p.success !== false,
      });
      return proceed();

    case 'task-complete':
      checkpointSession(common);
      return proceed();

    case 'task-cancel':
    case 'session-end':
      endSession({ ...common, reason: p.reason });
      return proceed();

    default:
      throw new Error(`unknown Cline hook event: ${event}`);
  }
}

function proceed() {
  return { stdout: { cancel: false }, exitCode: 0 };
}

/** Cline hook file names mapped to Provenant events. */
export const HOOK_FILES = Object.freeze({
  TaskStart: 'task-start',
  TaskResume: 'task-resume',
  UserPromptSubmit: 'prompt',
  PreToolUse: 'pre-tool',
  PostToolUse: 'post-tool',
  TaskComplete: 'task-complete',
  TaskCancel: 'task-cancel',
});

/**
 * Source of one hook script. Absolute paths are baked in so the hook does not
 * depend on the PATH Cline's extension host inherited.
 *
 * @param {{node: string, bin: string, event: string}} args
 */
export function hookScript({ node, bin, event }) {
  const q = (s) => `'${String(s).replace(/'/g, `'\\''`)}'`;
  return `#!/bin/sh
# Provenant hook for Cline — generated by \`provenant init --harness cline\`.
# Do not edit: re-run init to regenerate. All decisions are made by Provenant.
exec ${q(node)} ${q(bin)} hook cline ${event}
`;
}
