/**
 * OpenCode adapter.
 *
 * OpenCode extends through in-process plugins (`.opencode/plugins/*.js`) rather
 * than hook commands. The plugin Provenant installs is deliberately thin: it
 * forwards each event to `provenant hook opencode <event>` running under
 * Node, and throws when told to deny. All decisions happen here, in the same
 * gate every harness uses.
 *
 * Why a subprocess rather than importing the gate into OpenCode's process:
 * OpenCode runs plugins in Bun, and the gate's signing path depends on
 * `node:crypto` Ed25519 behaving exactly as Node's does. Running the gate in
 * Node keeps one tested code path for every harness, at the cost of a process
 * start per tool call. See docs/adr/0006-harness-adapters.md.
 *
 * OpenCode's `tool.execute.before` blocks by throwing and has no way to pause
 * for a human, so `ask` is resolved with a Provenant approval, as in Codex.
 */

import {
  gateToolCall,
  recordOutcome,
  recordPrompt,
  endSession,
  checkpointSession,
} from '../gate.js';
import { normalize, renderResponse, isErrorResponse, approvalMessage } from './common.js';

const HARNESS = 'opencode';

/**
 * @param {string} event
 * @param {object} payload
 * @returns {{stdout: object, exitCode: number}}
 */
export function handle(event, payload) {
  const p = normalize(payload);
  const common = { harnessSessionId: p.harnessSessionId, harness: HARNESS, cwd: p.cwd };

  switch (event) {
    case 'pre-tool': {
      if (!p.tool) return reply({ decision: 'allow' });
      const d = gateToolCall({ ...common, tool: p.tool, input: p.input, askMode: 'approval' });
      if (d.effect === 'allow') {
        return reply({ decision: 'allow', class: d.class, event: d.event });
      }
      return reply({
        decision: 'deny',
        class: d.class,
        event: d.event,
        policy: d.policy,
        ...(d.approval ? { approval: d.approval } : {}),
        reason:
          d.effect === 'ask'
            ? approvalMessage(d)
            : `Blocked by Provenant [${d.class}]: ${d.reason}`,
      });
    }

    case 'post-tool': {
      if (!p.tool) return reply({ ok: true });
      const r = recordOutcome({
        ...common,
        tool: p.tool,
        input: p.input,
        output: renderResponse(p.response),
        ok: !isErrorResponse(p.response?.metadata ?? p.response),
      });
      return reply({ ok: true, taint: r.taint });
    }

    case 'prompt': {
      recordPrompt({ ...common, prompt: p.prompt });
      return reply({ ok: true });
    }

    case 'idle': {
      const r = checkpointSession(common);
      return reply({ ok: true, root: r.checkpoint.root, size: r.checkpoint.size });
    }

    case 'session-end': {
      endSession({ ...common, reason: p.reason });
      return reply({ ok: true });
    }

    default:
      throw new Error(`unknown OpenCode event: ${event}`);
  }
}

function reply(stdout) {
  return { stdout, exitCode: 0 };
}

/** Tools the plugin may let through if Provenant itself cannot be reached. */
export const READ_ONLY_TOOLS = ['read', 'grep', 'glob', 'list', 'lsp', 'todoread', 'todowrite', 'question', 'skill'];

/**
 * Source of the plugin file `provenant init --harness opencode` writes.
 *
 * Absolute paths to Node and to the Provenant entry point are baked in, so the
 * plugin works however OpenCode was launched and whatever PATH it inherited.
 *
 * @param {{node: string, bin: string}} paths
 * @returns {string}
 */
export function pluginSource({ node, bin }) {
  return `// Provenant plugin for OpenCode — generated by \`provenant init --harness opencode\`.
// Do not edit: re-run init to regenerate. Every decision is made by Provenant
// itself (${JSON.stringify(bin)}); this file only forwards events and blocks on deny.
import { spawn } from "node:child_process";

const NODE = ${JSON.stringify(node)};
const BIN = ${JSON.stringify(bin)};
const TIMEOUT_MS = 15000;
// If Provenant cannot be reached, only these read-only tools are let through.
const READ_ONLY = new Set(${JSON.stringify(READ_ONLY_TOOLS)});

function hook(event, payload) {
  return new Promise((resolve) => {
    let out = "";
    let err = "";
    let settled = false;
    const done = (value) => {
      if (!settled) {
        settled = true;
        resolve(value);
      }
    };
    let child;
    try {
      child = spawn(NODE, [BIN, "hook", "opencode", event], { stdio: ["pipe", "pipe", "pipe"], windowsHide: true });
    } catch (e) {
      return done({ error: String(e && e.message ? e.message : e) });
    }
    const timer = setTimeout(() => {
      child.kill();
      done({ error: "timed out after " + TIMEOUT_MS + " ms" });
    }, TIMEOUT_MS);
    child.stdout.on("data", (d) => (out += d));
    child.stderr.on("data", (d) => (err += d));
    child.on("error", (e) => {
      clearTimeout(timer);
      done({ error: e.message });
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      if (code !== 0) return done({ error: firstError(err) || "exit code " + code });
      try {
        done({ result: out.trim() ? JSON.parse(out) : {} });
      } catch {
        done({ error: "unreadable reply from provenant" });
      }
    });
    child.stdin.end(JSON.stringify(payload));
  });
}

// One readable line for the agent, not a stack trace.
function firstError(text) {
  const lines = String(text || "").split(/\\r?\\n/).map((l) => l.trim()).filter(Boolean);
  return (lines.find((l) => /^(\\w*Error|provenant:)/.test(l)) || lines[0] || "").slice(0, 300);
}

function textOf(parts) {
  return (Array.isArray(parts) ? parts : [])
    .filter((p) => p && p.type === "text" && typeof p.text === "string")
    .map((p) => p.text)
    .join("\\n");
}

export const Provenant = async ({ directory }) => ({
  "tool.execute.before": async (input, output) => {
    const r = await hook("pre-tool", {
      session_id: input.sessionID,
      call_id: input.callID,
      cwd: directory,
      tool_name: input.tool,
      tool_input: output.args,
    });
    if (r.error) {
      // Fail closed: a guard that cannot decide must not become an open door.
      if (READ_ONLY.has(input.tool)) return;
      throw new Error("Provenant: gate unavailable (" + r.error + "); " + input.tool + " blocked. Run \`provenant doctor\`.");
    }
    if (r.result.decision !== "allow") {
      throw new Error(r.result.reason || "Blocked by Provenant");
    }
  },

  "tool.execute.after": async (input, output) => {
    await hook("post-tool", {
      session_id: input.sessionID,
      call_id: input.callID,
      cwd: directory,
      tool_name: input.tool,
      tool_input: input.args,
      tool_response: { output: output && output.output, title: output && output.title, metadata: output && output.metadata },
    });
  },

  "chat.message": async (input, output) => {
    await hook("prompt", {
      session_id: input.sessionID,
      cwd: directory,
      prompt: textOf(output && output.parts),
    });
  },

  event: async ({ event }) => {
    const sessionID = event && event.properties && (event.properties.sessionID || (event.properties.info && event.properties.info.id));
    if (!sessionID) return;
    if (event.type === "session.idle") await hook("idle", { session_id: sessionID, cwd: directory });
    if (event.type === "session.deleted") await hook("session-end", { session_id: sessionID, cwd: directory, reason: "deleted" });
  },
});
`;
}
